const theme = {
    colors: {
      transparent: 'transparent',
      white: 'white',
      peach: '#fac881',
      salmon: '#fec3a6',
      black: "#000",
      pink: "pink"
    },
    spacing: {
      tiny: 0.25 as const,
      quarterSm: 2 as const,
      quarter: 4 as const,
      demi: 8 as const,
      demiLG: 10 as const,
      demiXL: 12 as const,
      baseSm: 14 as const,
      base: 16 as const,
      baseLg: 20 as const,
      baseXl: 24 as const,
      screenPadding: 24 as const,
      doubleSm: 28 as const,
      double: 32 as const,
      triple: 48 as const,
      input: 56 as const,
      quadruple: 64 as const,
      quintuple: 80 as const,
      sixfold: 96 as const,
      octuple: 128 as const,
    },
    lineHeight: {
      tiny: 1.5 as const,
      md : 21 as const,
    },
    img:{
      mdLg: 300 as const,
    },
    fontSize: {
      xxs: 11 as const,
      xs: 12 as const,
      sm: 14 as const,
      md: 16 as const,
      lg: 18 as const,
      lg2: 20 as const,
      xl: 22 as const,
      xl2: 24 as const,
      xl3: 26 as const,
      xl5: 40 as const,
      xl6: 45 as const,
    },
    fontWeight: {
      normal: '400' as const,
      semibold: '600' as const,
      medium: '500' as const,
      bold: '700' as const,
    },
    radius: {
      full: 9999 as const,
      demi: 4 as const,
      base: 8 as const,
      baseLg: 10 as const,
      double: 20 as const,
      triple: 25 as const,
      quadruple: 32 as const,
    },
    opacity: {
      pressedSubtle: 0.75 as const,
      pressed: 0.5 as const,
    },
    fontFamily: {
      poppins400: 'Poppins-Regular',
      poppins500: 'Poppins-Medium',
      poppins600: 'Poppins-SemiBold',
      poppins700: 'Poppins-Bold',
      roboto400: 'Roboto-Regular',
      roboto500: 'Roboto-Medium',
      beyondTheMountains: 'BeyondTheMountains',
    },
    align:{
      center: 'center' as const,
      left: 'left' as const,
    }
  };
  
  export default theme;